# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(default='', max_length=17, verbose_name='vin')),
                ('number', models.CharField(default='', max_length=9, verbose_name='number')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='brand')),
                ('model', models.CharField(default='', max_length=255, verbose_name='model')),
                ('year', models.CharField(default='', max_length=4, verbose_name='year')),
                ('is_auction', models.BooleanField(db_index=True, default=False, verbose_name='is_auction')),
            ],
        ),
    ]
