# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0003_auto_20170928_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crash',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crash',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='service',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.DeleteModel(
            name='Crash',
        ),
        migrations.DeleteModel(
            name='CrashDescription',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
