# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0008_auto_20170928_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_avalible',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
    ]
