# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rat', '0009_auto_20170929_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerationExcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ControlExcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ControlTelemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.BigIntegerField(default=0, verbose_name='datetime')),
                ('torque', models.FloatField(default=0, verbose_name='torque')),
                ('breake', models.FloatField(default=0, verbose_name='breake')),
                ('rpm', models.FloatField(default=0, verbose_name='rpm')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rat.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LocationTelemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.BigIntegerField(default=0, verbose_name='datetime')),
                ('spd', models.FloatField(default=0, verbose_name='spd')),
                ('latitude', models.FloatField(default=0, verbose_name='latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='longitude')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rat.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedExcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0, verbose_name='limit')),
                ('loc_telemetry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Hardware.LocationTelemetry')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_telemetry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Hardware.LocationTelemetry')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.BigIntegerField(default=0, verbose_name='datetime')),
                ('fuel', models.FloatField(default=0, verbose_name='fuel')),
                ('acc_x', models.FloatField(default=0, verbose_name='acc_x')),
                ('acc_y', models.FloatField(default=0, verbose_name='acc_y')),
                ('acc_z', models.FloatField(default=0, verbose_name='acc_z')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rat.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='controlexcess',
            name='control_telemetry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Hardware.ControlTelemetry'),
        ),
        migrations.AddField(
            model_name='accelerationexcess',
            name='telemetry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Hardware.Telemetry'),
        ),
    ]
